### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by petermoore14** [dragoscirjan/aurelia-google-recaptcha#2]
Would it be possible to create a new version tag? Some of the recent updates are pretty important and probably warrant one.

**Comment by dragoscirjan** [comment]
Hi Peter,

I am more than willing to help, however I'm in vacation until September 20th.
If you're willing to wait, I can help you then. If not, maybe creating a fork and requesting for a merge would help faster :).

Best regards,
Dragos

**Comment by petermoore14** [comment]
Hey Dragos,

Thanks, no problem, not in a big rush on my end. Will make a PR for you if I have some downtime.

Cheers,

-Peter

**Comment by dragoscirjan** [comment]
@petermoore14 You probably wrote your own or used the [other existing plugin](https://www.npmjs.com/search?q=aurelia-google-recaptcha) until now. This one was updated and it supports all 3 versions of reCAPTCHA now :). Sorry for the long delay. Will try to be more active from now on.
